name: Build Android APK

on:
  push:
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Kodu İndir
        uses: actions/checkout@v4

      - name: Buildozer ile APK Derle
        uses: ArtemSBulgakov/buildozer-action@v1
        with:
          buildozer_version: latest
          command: buildozer android debug

      - name: APK Dosyasını Kaydet
        uses: actions/upload-artifact@v4
        with:
          name: Mr-Fridge-Android-APK
          path: bin/*.apk
